/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MainRouteImport } from './routes/main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardIndexRouteImport } from './routes/board/index'
import { Route as BoardWriteRouteImport } from './routes/board/write'
import { Route as BoardIdRouteImport } from './routes/board/$id'
import { Route as DocsCategoryIndexRouteImport } from './routes/docs/$category/index'
import { Route as DocsCategoryPostIdRouteImport } from './routes/docs/$category/$postId'
import { Route as BoardIdEditRouteImport } from './routes/board/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardWriteRoute = BoardWriteRouteImport.update({
  id: '/board/write',
  path: '/board/write',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdRoute = BoardIdRouteImport.update({
  id: '/board/$id',
  path: '/board/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCategoryIndexRoute = DocsCategoryIndexRouteImport.update({
  id: '/docs/$category/',
  path: '/docs/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCategoryPostIdRoute = DocsCategoryPostIdRouteImport.update({
  id: '/docs/$category/$postId',
  path: '/docs/$category/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdEditRoute = BoardIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BoardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/board/write': typeof BoardWriteRoute
  '/board': typeof BoardIndexRoute
  '/board/$id/edit': typeof BoardIdEditRoute
  '/docs/$category/$postId': typeof DocsCategoryPostIdRoute
  '/docs/$category': typeof DocsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/board/write': typeof BoardWriteRoute
  '/board': typeof BoardIndexRoute
  '/board/$id/edit': typeof BoardIdEditRoute
  '/docs/$category/$postId': typeof DocsCategoryPostIdRoute
  '/docs/$category': typeof DocsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRoute
  '/register': typeof RegisterRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/board/write': typeof BoardWriteRoute
  '/board/': typeof BoardIndexRoute
  '/board/$id/edit': typeof BoardIdEditRoute
  '/docs/$category/$postId': typeof DocsCategoryPostIdRoute
  '/docs/$category/': typeof DocsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/main'
    | '/register'
    | '/board/$id'
    | '/board/write'
    | '/board'
    | '/board/$id/edit'
    | '/docs/$category/$postId'
    | '/docs/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/main'
    | '/register'
    | '/board/$id'
    | '/board/write'
    | '/board'
    | '/board/$id/edit'
    | '/docs/$category/$postId'
    | '/docs/$category'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/main'
    | '/register'
    | '/board/$id'
    | '/board/write'
    | '/board/'
    | '/board/$id/edit'
    | '/docs/$category/$postId'
    | '/docs/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MainRoute: typeof MainRoute
  RegisterRoute: typeof RegisterRoute
  BoardIdRoute: typeof BoardIdRouteWithChildren
  BoardWriteRoute: typeof BoardWriteRoute
  BoardIndexRoute: typeof BoardIndexRoute
  DocsCategoryPostIdRoute: typeof DocsCategoryPostIdRoute
  DocsCategoryIndexRoute: typeof DocsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/write': {
      id: '/board/write'
      path: '/board/write'
      fullPath: '/board/write'
      preLoaderRoute: typeof BoardWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id': {
      id: '/board/$id'
      path: '/board/$id'
      fullPath: '/board/$id'
      preLoaderRoute: typeof BoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$category/': {
      id: '/docs/$category/'
      path: '/docs/$category'
      fullPath: '/docs/$category'
      preLoaderRoute: typeof DocsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$category/$postId': {
      id: '/docs/$category/$postId'
      path: '/docs/$category/$postId'
      fullPath: '/docs/$category/$postId'
      preLoaderRoute: typeof DocsCategoryPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id/edit': {
      id: '/board/$id/edit'
      path: '/edit'
      fullPath: '/board/$id/edit'
      preLoaderRoute: typeof BoardIdEditRouteImport
      parentRoute: typeof BoardIdRoute
    }
  }
}

interface BoardIdRouteChildren {
  BoardIdEditRoute: typeof BoardIdEditRoute
}

const BoardIdRouteChildren: BoardIdRouteChildren = {
  BoardIdEditRoute: BoardIdEditRoute,
}

const BoardIdRouteWithChildren =
  BoardIdRoute._addFileChildren(BoardIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MainRoute: MainRoute,
  RegisterRoute: RegisterRoute,
  BoardIdRoute: BoardIdRouteWithChildren,
  BoardWriteRoute: BoardWriteRoute,
  BoardIndexRoute: BoardIndexRoute,
  DocsCategoryPostIdRoute: DocsCategoryPostIdRoute,
  DocsCategoryIndexRoute: DocsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
