/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadIndexRouteImport } from './routes/thread/index'
import { Route as BoardIndexRouteImport } from './routes/board/index'
import { Route as ThreadWriteRouteImport } from './routes/thread/write'
import { Route as ThreadThreadIdRouteImport } from './routes/thread/$threadId'
import { Route as BoardWriteRouteImport } from './routes/board/write'
import { Route as BoardIdRouteImport } from './routes/board/$id'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthFindUserRouteImport } from './routes/auth/find-user'
import { Route as AuthFindPwdRouteImport } from './routes/auth/find-pwd'
import { Route as DocsCategoryIndexRouteImport } from './routes/docs/$category/index'
import { Route as ThreadThreadIdEditRouteImport } from './routes/thread/$threadId/edit'
import { Route as DocsCategoryChapterIdRouteImport } from './routes/docs/$category/$chapterId'
import { Route as BoardIdEditRouteImport } from './routes/board/$id/edit'

const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIndexRoute = ThreadIndexRouteImport.update({
  id: '/thread/',
  path: '/thread/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadWriteRoute = ThreadWriteRouteImport.update({
  id: '/thread/write',
  path: '/thread/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadThreadIdRoute = ThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardWriteRoute = BoardWriteRouteImport.update({
  id: '/board/write',
  path: '/board/write',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdRoute = BoardIdRouteImport.update({
  id: '/board/$id',
  path: '/board/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFindUserRoute = AuthFindUserRouteImport.update({
  id: '/auth/find-user',
  path: '/auth/find-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFindPwdRoute = AuthFindPwdRouteImport.update({
  id: '/auth/find-pwd',
  path: '/auth/find-pwd',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCategoryIndexRoute = DocsCategoryIndexRouteImport.update({
  id: '/docs/$category/',
  path: '/docs/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadThreadIdEditRoute = ThreadThreadIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ThreadThreadIdRoute,
} as any)
const DocsCategoryChapterIdRoute = DocsCategoryChapterIdRouteImport.update({
  id: '/docs/$category/$chapterId',
  path: '/docs/$category/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdEditRoute = BoardIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BoardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/auth/find-pwd': typeof AuthFindPwdRoute
  '/auth/find-user': typeof AuthFindUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/board/write': typeof BoardWriteRoute
  '/thread/$threadId': typeof ThreadThreadIdRouteWithChildren
  '/thread/write': typeof ThreadWriteRoute
  '/board': typeof BoardIndexRoute
  '/thread': typeof ThreadIndexRoute
  '/board/$id/edit': typeof BoardIdEditRoute
  '/docs/$category/$chapterId': typeof DocsCategoryChapterIdRoute
  '/thread/$threadId/edit': typeof ThreadThreadIdEditRoute
  '/docs/$category': typeof DocsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/auth/find-pwd': typeof AuthFindPwdRoute
  '/auth/find-user': typeof AuthFindUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/board/write': typeof BoardWriteRoute
  '/thread/$threadId': typeof ThreadThreadIdRouteWithChildren
  '/thread/write': typeof ThreadWriteRoute
  '/board': typeof BoardIndexRoute
  '/thread': typeof ThreadIndexRoute
  '/board/$id/edit': typeof BoardIdEditRoute
  '/docs/$category/$chapterId': typeof DocsCategoryChapterIdRoute
  '/thread/$threadId/edit': typeof ThreadThreadIdEditRoute
  '/docs/$category': typeof DocsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/auth/find-pwd': typeof AuthFindPwdRoute
  '/auth/find-user': typeof AuthFindUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/board/$id': typeof BoardIdRouteWithChildren
  '/board/write': typeof BoardWriteRoute
  '/thread/$threadId': typeof ThreadThreadIdRouteWithChildren
  '/thread/write': typeof ThreadWriteRoute
  '/board/': typeof BoardIndexRoute
  '/thread/': typeof ThreadIndexRoute
  '/board/$id/edit': typeof BoardIdEditRoute
  '/docs/$category/$chapterId': typeof DocsCategoryChapterIdRoute
  '/thread/$threadId/edit': typeof ThreadThreadIdEditRoute
  '/docs/$category/': typeof DocsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/auth/find-pwd'
    | '/auth/find-user'
    | '/auth/login'
    | '/auth/register'
    | '/board/$id'
    | '/board/write'
    | '/thread/$threadId'
    | '/thread/write'
    | '/board'
    | '/thread'
    | '/board/$id/edit'
    | '/docs/$category/$chapterId'
    | '/thread/$threadId/edit'
    | '/docs/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main'
    | '/auth/find-pwd'
    | '/auth/find-user'
    | '/auth/login'
    | '/auth/register'
    | '/board/$id'
    | '/board/write'
    | '/thread/$threadId'
    | '/thread/write'
    | '/board'
    | '/thread'
    | '/board/$id/edit'
    | '/docs/$category/$chapterId'
    | '/thread/$threadId/edit'
    | '/docs/$category'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/auth/find-pwd'
    | '/auth/find-user'
    | '/auth/login'
    | '/auth/register'
    | '/board/$id'
    | '/board/write'
    | '/thread/$threadId'
    | '/thread/write'
    | '/board/'
    | '/thread/'
    | '/board/$id/edit'
    | '/docs/$category/$chapterId'
    | '/thread/$threadId/edit'
    | '/docs/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRoute
  AuthFindPwdRoute: typeof AuthFindPwdRoute
  AuthFindUserRoute: typeof AuthFindUserRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BoardIdRoute: typeof BoardIdRouteWithChildren
  BoardWriteRoute: typeof BoardWriteRoute
  ThreadThreadIdRoute: typeof ThreadThreadIdRouteWithChildren
  ThreadWriteRoute: typeof ThreadWriteRoute
  BoardIndexRoute: typeof BoardIndexRoute
  ThreadIndexRoute: typeof ThreadIndexRoute
  DocsCategoryChapterIdRoute: typeof DocsCategoryChapterIdRoute
  DocsCategoryIndexRoute: typeof DocsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/': {
      id: '/thread/'
      path: '/thread'
      fullPath: '/thread'
      preLoaderRoute: typeof ThreadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/write': {
      id: '/thread/write'
      path: '/thread/write'
      fullPath: '/thread/write'
      preLoaderRoute: typeof ThreadWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$threadId': {
      id: '/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof ThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/write': {
      id: '/board/write'
      path: '/board/write'
      fullPath: '/board/write'
      preLoaderRoute: typeof BoardWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id': {
      id: '/board/$id'
      path: '/board/$id'
      fullPath: '/board/$id'
      preLoaderRoute: typeof BoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/find-user': {
      id: '/auth/find-user'
      path: '/auth/find-user'
      fullPath: '/auth/find-user'
      preLoaderRoute: typeof AuthFindUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/find-pwd': {
      id: '/auth/find-pwd'
      path: '/auth/find-pwd'
      fullPath: '/auth/find-pwd'
      preLoaderRoute: typeof AuthFindPwdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$category/': {
      id: '/docs/$category/'
      path: '/docs/$category'
      fullPath: '/docs/$category'
      preLoaderRoute: typeof DocsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$threadId/edit': {
      id: '/thread/$threadId/edit'
      path: '/edit'
      fullPath: '/thread/$threadId/edit'
      preLoaderRoute: typeof ThreadThreadIdEditRouteImport
      parentRoute: typeof ThreadThreadIdRoute
    }
    '/docs/$category/$chapterId': {
      id: '/docs/$category/$chapterId'
      path: '/docs/$category/$chapterId'
      fullPath: '/docs/$category/$chapterId'
      preLoaderRoute: typeof DocsCategoryChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id/edit': {
      id: '/board/$id/edit'
      path: '/edit'
      fullPath: '/board/$id/edit'
      preLoaderRoute: typeof BoardIdEditRouteImport
      parentRoute: typeof BoardIdRoute
    }
  }
}

interface BoardIdRouteChildren {
  BoardIdEditRoute: typeof BoardIdEditRoute
}

const BoardIdRouteChildren: BoardIdRouteChildren = {
  BoardIdEditRoute: BoardIdEditRoute,
}

const BoardIdRouteWithChildren =
  BoardIdRoute._addFileChildren(BoardIdRouteChildren)

interface ThreadThreadIdRouteChildren {
  ThreadThreadIdEditRoute: typeof ThreadThreadIdEditRoute
}

const ThreadThreadIdRouteChildren: ThreadThreadIdRouteChildren = {
  ThreadThreadIdEditRoute: ThreadThreadIdEditRoute,
}

const ThreadThreadIdRouteWithChildren = ThreadThreadIdRoute._addFileChildren(
  ThreadThreadIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRoute,
  AuthFindPwdRoute: AuthFindPwdRoute,
  AuthFindUserRoute: AuthFindUserRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BoardIdRoute: BoardIdRouteWithChildren,
  BoardWriteRoute: BoardWriteRoute,
  ThreadThreadIdRoute: ThreadThreadIdRouteWithChildren,
  ThreadWriteRoute: ThreadWriteRoute,
  BoardIndexRoute: BoardIndexRoute,
  ThreadIndexRoute: ThreadIndexRoute,
  DocsCategoryChapterIdRoute: DocsCategoryChapterIdRoute,
  DocsCategoryIndexRoute: DocsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
